// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcp2MJfOT4_TE5QwfP5Cyio8KMR9nee9k',
    appId: '1:808728101899:web:74d5642bf52f8476e9730e',
    messagingSenderId: '808728101899',
    projectId: 'assignment-staredu',
    authDomain: 'assignment-staredu.firebaseapp.com',
    storageBucket: 'assignment-staredu.appspot.com',
    measurementId: 'G-MQBZRH3L5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfCaUjkP2fo4Ija0vv7lHjyl7j92AMeuM',
    appId: '1:808728101899:android:a987665c1292a779e9730e',
    messagingSenderId: '808728101899',
    projectId: 'assignment-staredu',
    storageBucket: 'assignment-staredu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC69CQCRx6E8t3v0Y0kskXiayx9UQptRqk',
    appId: '1:808728101899:ios:767b3c1c01c00c65e9730e',
    messagingSenderId: '808728101899',
    projectId: 'assignment-staredu',
    storageBucket: 'assignment-staredu.appspot.com',
    iosBundleId: 'com.example.assignmentStaredu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC69CQCRx6E8t3v0Y0kskXiayx9UQptRqk',
    appId: '1:808728101899:ios:767b3c1c01c00c65e9730e',
    messagingSenderId: '808728101899',
    projectId: 'assignment-staredu',
    storageBucket: 'assignment-staredu.appspot.com',
    iosBundleId: 'com.example.assignmentStaredu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcp2MJfOT4_TE5QwfP5Cyio8KMR9nee9k',
    appId: '1:808728101899:web:d77bba12bdf69108e9730e',
    messagingSenderId: '808728101899',
    projectId: 'assignment-staredu',
    authDomain: 'assignment-staredu.firebaseapp.com',
    storageBucket: 'assignment-staredu.appspot.com',
    measurementId: 'G-8MVLW4MMLX',
  );

}